const RANKING_COPY = {
  boardNames: {
    week: "周榜",
    career: "生涯榜",
    strength: "实力榜",
    season: "赛季榜",
  },
  emptyGlobal: (boardName) => `${boardName}还没有人入榜。第一场预测结算后，你就是第一名`,
  emptyGroup: (boardName) => `${boardName}还没有人入榜。第一场预测结算后，你就是第一名`,
  emptyGeneric: "暂无排行数据",
  goPredict: "去预测",
  inviteGlobal: "邀请好友建个群，看看谁更懂球",
  inviteGroup: "邀请好友加入这个群",
  inviteAction: "邀请好友",
  noGroups: "我的群（创建或加入后解锁）",
  groupFeatureSoon: "群功能即将开放",
  groupsTitle: "预言群",
  groupsEmpty: "你还没有加入任何群",
  groupDescription: "每个群独立排名，在群里和朋友比一比谁更懂球",
  groupLimits: (joined, owned) => `最多加入 ${joined} 个群、创建 ${owned} 个群`,
  createGroup: "创建我的预言群",
  joinGroup: "输入邀请码加入",
  inviteCode: "邀请码",
  inviteCodePlaceholder: "输入 8 位邀请码",
  joinConfirm: "加入预言群",
  confirmJoin: "加入",
  groupJoinSubtitle: "输入群主分享的邀请码",
  groupInviteFormat: "由 8 位大写字母和数字组成",
  groupInviteRemaining: (count) => count === 0 ? "邀请码已填完整" : `还差 ${count} 位`,
  groupCreateSubtitle: "把邀请码发给朋友",
  groupDetailTitle: "群详情",
  shareGroup: "邀请好友",
  copyInviteCode: "复制邀请码",
  inviteCodeCopied: "邀请码已复制",
  leaveGroup: "退出群",
  dissolveGroup: "解散群",
  groupSharedTitle: "来一起比预测成绩",
  groupLoadFailed: "读取群信息失败",
  groupActionFailed: "操作失败，请重试",
  groupMembershipChanged: "群成员状态已变化，请重新选择群",
  groupMemberCount: (count) => `${count} 位成员`,
  groupOwnerRole: "群主",
  groupMemberRole: "成员",
  groupJoinErrors: {
    GROUP_NOT_FOUND: "邀请码无效，群不存在",
    GROUP_DISSOLVED: "该群已解散",
    GROUP_ALREADY_MEMBER: "你已经加入这个群",
    GROUP_MEMBER_LIMIT_REACHED: "该群人数已满",
    GROUP_JOIN_LIMIT_REACHED: "已达到加入群数量上限",
    INVALID_INVITE_CODE: "请输入有效的 8 位邀请码",
  },
  groupRetry: "重试",
  groupInvalidInvite: "邀请码缺失或格式不正确",
  groupInviteCodeLabel: "群邀请码",
  groupRoleText: (role) => role === "owner" ? "群主" : "成员",
  groupLeaveConfirm: "确定退出这个群吗？",
  groupDissolveConfirm: "解散后所有成员将退出，确定解散吗？",
  groupCreateSuccess: "创建成功",
  groupJoinSuccess: "已加入群",
  groupLeaveSuccess: "已退出群",
  groupDissolveSuccess: "群已解散",
  groupNoInviteCode: "分享链接无效，请重新获取邀请码",
  groupCreateLimitReached: "已达到创建群数量上限",
  groupReLogin: "登录后即可加入群",
  guest: "请登录查看榜单",
  firstSeasonCareer: "你正在第一个赛季，生涯榜与赛季榜内容相同",
  seasonStarting: "赛季刚开始，名次变化会比较大",
  awaitingFinal: "等待最终确认",
  recap: (points, level) => `上赛季你拿了 ${points} 分，最高到 Lv${level}`,
  updatedNow: "刚刚更新",
  updatedMinutes: (count) => `更新于 ${count} 分钟前`,
  updatedHours: (count) => `更新于 ${count} 小时前`,
  updatedDays: (count) => `更新于 ${count} 天前`,
  allPeople: (count) => `全部 ${count} 位预言家`,
  globalTop: "全站前 20",
  groupTop: "群内前 20",
  currentWeek: "本周",
  pageTitle: "我的排行",
  scopeGlobal: "全站",
  scopeGroup: "我的群",
  emptyGuestLine: "请登录查看榜单",
};

module.exports = RANKING_COPY;
