/**
 * 数据库 Collection schema 定义（规范第 21 节）。
 *
 * 字段类型与可空性严格按规范；核心业务文档均带 schema_version = 1（2.5）。
 * 业务公式不在此定义，只描述存储契约。
 */
import {
  AdminAuditAction,
  AdminAuditEntityType,
} from "../domain/enums.js";

export type FieldType = "string" | "int" | "bool" | "date" | "object" | "array" | "null";

export interface FieldDef {
  type: FieldType;
  nullable?: boolean;
  required?: boolean;
  immutable?: boolean;
  unique?: boolean;
  enum?: readonly (string | number)[];
  min?: number;
  max?: number;
  default?: unknown;
  note?: string;
}

export interface CollectionDef {
  collection: string;
  fields: Record<string, FieldDef>;
  note?: string;
}

export const COLLECTION_DEFINITIONS: readonly CollectionDef[] = [
  {
    collection: "users",
    fields: {
      user_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      openid: { type: "string", required: true, unique: true },
      unionid: { type: "string", nullable: true },
      nickname: { type: "string", nullable: true },
      favorite_team_id: { type: "string", nullable: true, note: "UUID" },
      status: { type: "string", required: true, enum: ["active", "deleted"] },
      career_points: { type: "int", required: true, min: 0, default: 0 },
      career_valid_predictions: { type: "int", required: true, min: 0, default: 0 },
      career_wdl_hits: { type: "int", required: true, min: 0, default: 0 },
      career_exact_hits: { type: "int", required: true, min: 0, default: 0 },
      career_level: { type: "int", required: true, min: 1, max: 8, default: 1 },
      career_best_level: { type: "int", required: true, min: 1, max: 8, default: 1 },
      deleted_at: { type: "date", nullable: true },
      created_at: { type: "date", required: true, immutable: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "career_* 为可重建缓存；事实来源是 settlements / settlement_items（0.5）",
  },
  {
    collection: "user_season_stats",
    fields: {
      user_id: { type: "string", required: true, note: "UUID" },
      season_id: { type: "string", required: true },
      points: { type: "int", required: true, min: 0, default: 0 },
      valid_predictions: { type: "int", required: true, min: 0, default: 0 },
      wdl_hits: { type: "int", required: true, min: 0, default: 0 },
      exact_hits: { type: "int", required: true, min: 0, default: 0 },
      level: { type: "int", required: true, min: 1, max: 8, default: 1 },
      best_level: { type: "int", required: true, min: 1, max: 8, default: 1 },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(user_id, season_id)",
  },
  {
    collection: "teams",
    fields: {
      team_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      name: { type: "string", required: true },
      short_name: { type: "string", nullable: true },
      primary_color: { type: "string", nullable: true, note: "#RRGGBB" },
      secondary_color: { type: "string", nullable: true, note: "#RRGGBB" },
      status: { type: "string", required: true, enum: ["active", "inactive"] },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
  },
  {
    collection: "team_provider_mappings",
    fields: {
      team_id: { type: "string", required: true, note: "UUID" },
      provider: { type: "string", required: true, enum: ["api_football"] },
      provider_team_id: { type: "string", required: true },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(provider, provider_team_id)",
  },
  {
    collection: "matches",
    fields: {
      match_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      league_id: { type: "string", required: true, default: "premier_league" },
      season_id: { type: "string", required: true, default: "2026_2027" },
      round_id: { type: "string", required: true, immutable: true, note: "01..38" },
      home_team_id: { type: "string", required: true, note: "UUID" },
      away_team_id: { type: "string", required: true, note: "UUID" },
      kickoff_at: { type: "date", required: true },
      kickoff_confirmed: { type: "bool", required: true },
      prediction_deadline_at: { type: "date", nullable: true },
      prediction_closed_at: { type: "date", nullable: true, note: "一旦写入 immutable" },
      period_anchor_at: { type: "date", nullable: true, note: "一旦写入 immutable" },
      match_status: {
        type: "string",
        required: true,
        enum: ["scheduled", "live", "finished", "postponed", "cancelled", "abandoned"],
      },
      settlement_status: {
        type: "string",
        required: true,
        enum: ["pending", "waiting", "settling", "settled", "correcting", "failed", "voided"],
      },
      regular_home_score: { type: "int", nullable: true, min: 0, max: 99 },
      regular_away_score: { type: "int", nullable: true, min: 0, max: 99 },
      extra_home_score: { type: "int", nullable: true, min: 0, max: 99 },
      extra_away_score: { type: "int", nullable: true, min: 0, max: 99 },
      penalty_home_score: { type: "int", nullable: true, min: 0, max: 99 },
      penalty_away_score: { type: "int", nullable: true, min: 0, max: 99 },
      result_version: { type: "int", required: true, min: 0, default: 0 },
      settled_result_version: { type: "int", required: true, min: 0, default: 0 },
      result_source: { type: "string", nullable: true, enum: ["provider", "admin"] },
      scoring_rule_version: { type: "string", required: true, default: "scoring_v1" },
      finish_detected_at: { type: "date", nullable: true, note: "一旦写入 immutable" },
      settled_at: { type: "date", nullable: true },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "MVP 英超：extra_*/penalty_* 正常值必须为 null，自动结算不得使用",
  },
  {
    collection: "match_provider_mappings",
    fields: {
      match_id: { type: "string", required: true, note: "UUID" },
      provider: { type: "string", required: true, enum: ["api_football"] },
      provider_match_id: { type: "string", required: true },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(provider, provider_match_id)",
  },
  {
    collection: "match_results",
    fields: {
      match_id: { type: "string", required: true, note: "UUID" },
      result_version: { type: "int", required: true, min: 1 },
      regular_home_score: { type: "int", required: true, min: 0, max: 99 },
      regular_away_score: { type: "int", required: true, min: 0, max: 99 },
      source: { type: "string", required: true, enum: ["provider", "admin"] },
      provider_status: { type: "string", nullable: true },
      admin_id: { type: "string", nullable: true, note: "UUID" },
      reason: { type: "string", nullable: true, min: 1, max: 500 },
      created_at: { type: "date", required: true, immutable: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "immutable；UNIQUE(match_id, result_version)；provider: admin_id=null, reason=null；admin: admin_id+reason 必填",
  },
  {
    collection: "predictions",
    fields: {
      prediction_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      user_id: { type: "string", required: true, immutable: true, note: "UUID" },
      match_id: { type: "string", required: true, immutable: true, note: "UUID" },
      idempotency_key: { type: "string", required: true, immutable: true, note: "UUID" },
      pred_home_score: { type: "int", required: true, immutable: true, min: 0, max: 20 },
      pred_away_score: { type: "int", required: true, immutable: true, min: 0, max: 20 },
      derived_result: { type: "string", required: true, immutable: true, enum: ["HOME", "DRAW", "AWAY"] },
      submitted_at: { type: "date", required: true, immutable: true },
      scoring_rule_version: { type: "string", required: true, immutable: true, default: "scoring_v1" },
      match_score: { type: "int", nullable: true, enum: [0, 3, 12] },
      wdl_hit: { type: "bool", nullable: true },
      exact_hit: { type: "bool", nullable: true },
      applied_result_version: { type: "int", required: true, min: 0, default: 0 },
      created_at: { type: "date", required: true, immutable: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(user_id, match_id) + UNIQUE(user_id, idempotency_key)；不可修改/删除（8.5）",
  },
  {
    collection: "rankings",
    fields: {
      period_type: { type: "string", required: true, enum: ["week", "month"] },
      period_key: { type: "string", required: true },
      user_id: { type: "string", required: true, note: "UUID" },
      period_score: { type: "int", required: true, min: 0 },
      valid_predictions: { type: "int", required: true, min: 1 },
      wdl_hits: { type: "int", required: true, min: 0 },
      exact_hits: { type: "int", required: true, min: 0 },
      last_scoring_match_at: { type: "date", nullable: true },
      global_rank: { type: "int", nullable: true, min: 1 },
      is_final: { type: "bool", required: true, default: false },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(period_type, period_key, user_id)；不持久化浮点准确率",
  },
  {
    collection: "settlements",
    fields: {
      settlement_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      match_id: { type: "string", required: true, note: "UUID" },
      result_version: { type: "int", required: true, min: 1 },
      rule_version: { type: "string", required: true },
      status: { type: "string", required: true, enum: ["pending", "running", "settled", "failed"] },
      phase: {
        type: "string",
        required: true,
        enum: ["prepare", "apply_items", "rebuild_ranks", "finalize", "done"],
      },
      is_correction: { type: "bool", required: true },
      started_at: { type: "date", nullable: true },
      settled_at: { type: "date", nullable: true },
      attempt_count: { type: "int", required: true, min: 0, default: 0 },
      last_error_code: { type: "string", nullable: true },
      last_error_message: { type: "string", nullable: true },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(match_id, result_version, rule_version)",
  },
  {
    collection: "settlement_items",
    fields: {
      settlement_id: { type: "string", required: true, note: "UUID" },
      prediction_id: { type: "string", required: true, note: "UUID" },
      user_id: { type: "string", required: true, note: "UUID" },
      old_score: { type: "int", required: true, enum: [0, 3, 12] },
      new_score: { type: "int", required: true, enum: [0, 3, 12] },
      score_delta: { type: "int", required: true, note: "new - old" },
      old_wdl_hit: { type: "bool", required: true },
      new_wdl_hit: { type: "bool", required: true },
      old_exact_hit: { type: "bool", required: true },
      new_exact_hit: { type: "bool", required: true },
      valid_prediction_delta: { type: "int", required: true, enum: [0, 1] },
      source_result_version: { type: "int", required: true, min: 1 },
      status: { type: "string", required: true, enum: ["pending", "applied", "failed"] },
      applied_at: { type: "date", nullable: true },
      attempt_count: { type: "int", required: true, min: 0, default: 0 },
      last_error_code: { type: "string", nullable: true },
      last_error_message: { type: "string", nullable: true },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(settlement_id, prediction_id)",
  },
  {
    collection: "unlocks",
    fields: {
      unlock_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      user_id: { type: "string", required: true, note: "UUID" },
      unlock_code: { type: "string", required: true },
      threshold_points: { type: "int", required: true, min: 0 },
      source_version: { type: "string", required: true },
      unlocked_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(user_id, unlock_code)；已解锁永不回收",
  },
  {
    collection: "level_history",
    fields: {
      level_history_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      user_id: { type: "string", required: true, note: "UUID" },
      scope: { type: "string", required: true, enum: ["season", "career"] },
      season_id: { type: "string", nullable: true },
      from_level: { type: "int", required: true, min: 1, max: 8 },
      to_level: { type: "int", required: true, min: 1, max: 8 },
      wdl_hits: { type: "int", required: true, min: 0 },
      valid_predictions: { type: "int", required: true, min: 0 },
      reason: { type: "string", required: true, enum: ["settlement", "correction", "rebuild", "season_start"] },
      changed_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "scope=season 时 season_id 必填；scope=career 时 null；仅 from != to 时写入",
  },
  {
    collection: "admin_audit_logs",
    fields: {
      audit_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      admin_id: { type: "string", required: true, note: "UUID" },
      action: {
        type: "string",
        required: true,
        enum: [
          AdminAuditAction.ResultCorrection,
          AdminAuditAction.RetrySettlement,
          AdminAuditAction.RebuildUserStats,
          AdminAuditAction.RebuildRankings,
        ],
      },
      entity_type: {
        type: "string",
        required: true,
        enum: [
          AdminAuditEntityType.Match,
          AdminAuditEntityType.Settlement,
          AdminAuditEntityType.User,
          AdminAuditEntityType.RankingPeriod,
        ],
      },
      entity_id: { type: "string", required: true },
      old_value: { type: "object", nullable: true },
      new_value: { type: "object", nullable: true },
      reason: { type: "string", required: true, min: 1, max: 500 },
      created_at: { type: "date", required: true, immutable: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "immutable",
  },
  {
    collection: "admins",
    fields: {
      admin_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      openid: { type: "string", required: true, unique: true },
      status: { type: "string", required: true, enum: ["active", "disabled"] },
      role: { type: "string", required: true, enum: ["admin"] },
      created_at: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(openid)；管理员由部署配置显式 provision，无创建 API",
  },
  {
    collection: "provider_snapshots",
    fields: {
      snapshot_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      provider: { type: "string", required: true, enum: ["api_football"] },
      entity_type: { type: "string", required: true, enum: ["match", "team"] },
      entity_id: { type: "string", nullable: true, note: "UUID" },
      provider_entity_id: { type: "string", required: true },
      event_type: {
        type: "string",
        required: true,
        enum: [
          "discovered",
          "kickoff_changed",
          "status_changed",
          "result_observed",
          "result_changed",
          "provider_error",
          "provider_conflict",
          "admin_conflict",
        ],
      },
      payload: { type: "object", required: true },
      created_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "关键快照不自动清理",
  },
  {
    collection: "sync_logs",
    fields: {
      sync_job_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      job_type: {
        type: "string",
        required: true,
        enum: [
          "future_schedule",
          "full_schedule_verify",
          "near_match",
          "live_match",
          "post_finish_verify",
          "period_finalize",
          "daily_consistency",
        ],
      },
      status: { type: "string", required: true, enum: ["running", "success", "failed"] },
      started_at: { type: "date", required: true },
      finished_at: { type: "date", nullable: true },
      attempt_count: { type: "int", required: true, min: 0 },
      items_read: { type: "int", required: true, min: 0 },
      items_changed: { type: "int", required: true, min: 0 },
      items_failed: { type: "int", required: true, min: 0 },
      last_error_code: { type: "string", nullable: true },
      last_error_message: { type: "string", nullable: true },
      created_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "普通 sync_logs 保留 30 天",
  },
  {
    collection: "anomalies",
    fields: {
      anomaly_id: { type: "string", required: true, immutable: true, note: "UUID v4" },
      anomaly_key: { type: "string", required: true, unique: true, note: "match_id:type" },
      match_id: { type: "string", required: true, note: "UUID" },
      type: {
        type: "string",
        required: true,
        enum: [
          "LIVE_SYNC_STALE",
          "LIVE_TOO_LONG",
          "FINISHED_NO_SCORE",
          "INVALID_FINAL_SCORE",
          "PROVIDER_STATE_CONFLICT",
          "PROVIDER_DATA_INVALID",
          "UNEXPECTED_PROVIDER_STATUS",
          "TEAM_CHANGE_AFTER_PREDICTION",
          "KICKOFF_CHANGE_AFTER_ANCHOR",
          "ADMIN_PROVIDER_RESULT_CONFLICT",
        ],
      },
      blocking: { type: "bool", required: true },
      status: { type: "string", required: true, enum: ["open", "resolved"] },
      first_seen_at: { type: "date", required: true },
      last_seen_at: { type: "date", required: true },
      occurrence_count: { type: "int", required: true, min: 1 },
      details: { type: "object", required: true },
      resolved_at: { type: "date", nullable: true },
      resolution: { type: "string", nullable: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(anomaly_key)；同 match+type 重复出现更新同一记录",
  },
  {
    collection: "job_locks",
    fields: {
      lock_key: { type: "string", required: true, unique: true },
      owner_id: { type: "string", required: true },
      lease_until: { type: "date", required: true },
      updated_at: { type: "date", required: true },
      schema_version: { type: "int", required: true, default: 1 },
    },
    note: "UNIQUE(lock_key)；获取锁必须原子 compare-and-set，过期 lease 可接管",
  },
] as const;
